# Exercício

Escreva uma função `fliplr` que recebe um array 2D e altera o 
array espelhado-o horizontalmente, ou seja, as colunas à esquerda 
são trocadas com as da direita.

```python
    import numpy as np
    def main():
        a = np.array( [1,2,3,4,5,6,7,8,9,0] ).reshape(2,5)
        print(a)
        fliplr(a)
        print(a)
    main()

    Saída:
    [[1 2 3 4 5]
     [6 7 8 9 0]]
    [[5 4 3 2 1]
     [0 9 8 7 6]]

```

In [ ]:
import numpy as np

In [ ]:
def main():
    a = np.array( [1,2,3,4,5,6,7,8,9,0] ).reshape(2,5)
    print(a)
    fliplr(a)
    print(a)

In [ ]:
```python
[[1 2 3 4 5]
 [6 7 8 9 0]]
[[5 4 3 2 1]
 [0 9 8 7 6]]
```

In [ ]:

def fliplr( ar ):
    ''' (array) -> array 
    espelha as colunas.
    '''
    nlin, ncol = ar.shape
    meio = ncol // 2

    for i in range(meio):
        fim = ncol-1-i
        temp = ar[:,i].copy()  ## lembre-se que fatias são vistas!
        ar[:,i] = ar[:,fim]
        ar[:,fim] = temp
main()