# Exercício

Qual o comportamento geral dos 4 operadores básicos com arrays?

In [ ]:
import numpy as np

# Exercício

Usando a Classe Array2D da aula passada, escreva o método reshape( newshape ), que retorna uma vista dos mesmos dados com um novo shape.

``` python
    >>> a = Array2D( (2,3), 1)
    >>> print(a)
    1 1 1
    1 1 1
    >>> b = a.reshape(3,2)
    >>> print(b)
    1 1
    1 1
    1 1
    >>> b.data[2] = 0
    >>> print(a)
    1 1 0
    1 1 1
```


In [ ]:
def reshape(self, newshape):
    ''' (Array2d, shape) => vista '''

In [ ]:
# Exercício

Escreva agora o método copy(), que retorna o clone de um Array2D (os dados são clonados, não há compartilhamento de dados).

``` python
    >>> a = Array2D( (2,3), 1)
    >>> print(a)
    1 1 1
    1 1 1
    >>> b = a.reshape(3,2)
    >>> print(b)
    1 1
    1 1
    1 1
    >>> c = b.reshape(1,6).copy()
    >>> print(c)
    1 1 1 1 1 1
    >>> c.data[2] = 0
    >>> print(b)
    1 1
    1 1
    1 1
    >>> b.data[2] = 0
    >>> print(a)
    1 1 0
    1 1 1
```


In [ ]:
def copy(self):
    ''' (Array2D) -> Array2D '''
    

# Exercício

Escreva uma função `fliplr` que recebe um array 2D e altera o 
array espelhado-o horizontalmente, ou seja, as colunas à esquerda 
são trocadas com as da direita.

```python
    import numpy as np
    def main():
        a = np.array( [1,2,3,4,5,6,7,8,9,0] ).reshape(2,5)
        print(a)
        fliplr(a)
        print(a)
    main()

    Saída:
    [[1 2 3 4 5]
     [6 7 8 9 0]]
    [[5 4 3 2 1]
     [0 9 8 7 6]]

```

In [ ]:
def fliplr( a ):
    ''' (array) -> array '''
    